name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v3.6.0
    - name: Adding nightly toolchain
      run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - name: Adding llvm tools
      run: rustup component add llvm-tools-preview
    - name: Adding bootimage lib
      run: cargo install bootimage
    - name: Build Bootable Image
      run: cargo bootimage --target x86_64-unit_os.json
    - name: Build
      run: cargo build --verbose
    - name: List Target Directory Contents
      run: ls -R target/x86_64-unit_os/debug/deps
    - name: Run tests
      run: cargo test --verbose
