name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker Setup QEMU
      id: qemu-setup
      uses: docker/setup-qemu-action@v3.6.0
    - name: Find QEMU Executable (Attempt 2)
      run: |
        QEMU_PATH=$(which qemu-system-x86_64)
        if [ -n "$QEMU_PATH" ]; then
          echo "QEMU_BIN=$QEMU_PATH" >> $GITHUB_ENV
          echo "Found QEMU at: $QEMU_PATH"
        else
          echo "QEMU not found in PATH. Trying to find it in common action tool directories..."
          find /opt/hostedtoolcache /usr/local /usr/bin /opt -name "qemu-system-x86_64" -executable -print0 | while IFS= read -r -d $'\0' QEMU_PATH
          do
            if [ -n "$QEMU_PATH" ]; then
              echo "QEMU_BIN=$QEMU_PATH" >> $GITHUB_ENV
              echo "Found QEMU at: $QEMU_PATH"
              break
            fi
          done
          if [ -z "$QEMU_BIN" ]; then
            echo "Error: Could not find qemu-system-x86_64."
            exit 1
          fi
        fi
    - name: Adding nightly toolchain
      run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - name: Adding llvm tools
      run: rustup component add llvm-tools-preview
    - name: Adding bootimage lib
      run: cargo install bootimage
    - name: Build
      run: cargo build --verbose
    - name: Run tests with custom script
      run: ./run_tests.sh
