name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker Image
      run: docker build -t my-custom-os-dev-image . -f Dockerfile
    - name: Cargo Build
      run: |
        docker run --rm -v $(pwd):/app my-custom-os-dev-image /bin/bash -c "
          cd /app && 
          cargo build --target x86_64-unit_os.json
        "
    - name: Cargo Test
      run: |
        docker run --rm -v $(pwd):/app my-custom-os-dev-image /bin/bash -c "
          cd /app && 
          cargo test --target x86_64-unit_os.json
        "
