name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3.6.0
    - name: Set up environment for QEMU
      run: |
        echo "PATH=$PATH" >> $GITHUB_ENV
        echo "QEMU_PLATFORMS=${{ steps.qemu-setup.outputs.platforms }}" >> $GITHUB_ENV
    - name: Adding nightly toolchain
      run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - name: Adding llvm tools
      run: rustup component add llvm-tools-preview
    - name: Adding bootimage lib
      run: cargo install bootimage
    - name: Build
      run: cargo build --verbose
    - name: Run tests with custom script
      run: chmod +x run_tests.sh; ./run_tests.sh
